"""Surface energy balance with analytically constructed radiative equilibrium.

Checks solve4temp's conductive/sensible/radiative balance in W/m², using
saturated air to eliminate latent flux at a known subfreezing equilibrium.
No golden values are generated by the solver itself.
"""

import numpy as np
import pytest
from conftest import StateFactory

from veris.solve4temp import solve4temp
from veris.state import Settings


@pytest.mark.parametrize("snow", [0.0, 0.05, 0.3])
@pytest.mark.parametrize("temperature", [250.0, 260.0, 270.0])
def test_constructed_surface_energy_equilibrium(
    state: StateFactory, sett: Settings, snow: float, temperature: float
) -> None:
    shape = (3, 5)
    ones = np.ones(shape)
    freezing = sett.celsius2K + sett.tempFrz
    thickness = 1.5
    conductivity = 1 / (thickness / sett.iceConduct + snow / sett.snowConduct)
    conduction = conductivity * (freezing - temperature)
    emissivity = sett.snowEmiss if snow else sett.iceEmiss
    # Choose downwelling longwave to balance exactly the conductive flux.
    longwave = sett.stefBoltz * temperature**4 - conduction / emissivity
    assert longwave > sett.minLWdown
    vapor_pressure = 10 ** (12.537 - 2663.5 / temperature)
    humidity = 0.622 * vapor_pressure / (100000 - 0.378 * vapor_pressure)
    vs = state(
        LWdown=longwave * ones,
        SWdown=0 * ones,
        ATemp=temperature * ones,
        aqh=humidity * ones,
        wSpeed=5 * ones,
        fCori=1e-4 * ones,
    )
    result = solve4temp(
        vs,
        sett,
        thickness * ones,
        snow * ones,
        (temperature + 2) * ones,
        freezing * ones,
    )
    expected = (temperature, conduction, 0, 0, 0)
    for actual, reference in zip(result, expected):
        assert actual.shape == shape
        np.testing.assert_allclose(actual, reference, atol=1e-10)


@pytest.mark.parametrize("snow", [0.0, 0.1])
def test_absent_ice_has_no_flux_and_preserves_temperature(
    state: StateFactory, sett: Settings, snow: float
) -> None:
    ones = np.ones((3, 5))
    vs = state(
        LWdown=300 * ones,
        SWdown=200 * ones,
        ATemp=270 * ones,
        aqh=0.003 * ones,
        wSpeed=3 * ones,
        fCori=-1e-4 * ones,
    )
    result = solve4temp(vs, sett, 0 * ones, snow * ones, 265 * ones, 271 * ones)
    np.testing.assert_array_equal(result[0], 265 * ones)
    for flux in result[1:]:
        np.testing.assert_array_equal(flux, 0 * ones)


@pytest.mark.parametrize("south", [False, True])
@pytest.mark.parametrize("wet", [False, True])
@pytest.mark.parametrize("snow", [0.0, 0.05, 0.3])
def test_shortwave_transmission_and_snow_opacity(
    state: StateFactory, sett: Settings, south: bool, wet: bool, snow: float
) -> None:
    sett = sett._replace(dryIceAlb_south=0.72, wetIceAlb_south=0.61)
    ones = np.ones((3, 5))
    vs = state(
        LWdown=300 * ones,
        SWdown=200 * ones,
        ATemp=270 * ones,
        aqh=0.003 * ones,
        wSpeed=3 * ones,
        fCori=(-1 if south else 1) * ones,
    )
    initial_temperature = sett.celsius2K if wet else 260
    result = solve4temp(
        vs, sett, 1.2 * ones, snow * ones, initial_temperature * ones, 271 * ones
    )
    suffix = "_south" if south else ""
    albedo = getattr(sett, ("wetIceAlb" if wet else "dryIceAlb") + suffix)
    expected = 0 if snow else -200 * (1 - albedo) * sett.shortwave * np.exp(-1.5 * 1.2)
    np.testing.assert_allclose(result[3], expected, atol=1e-12)
    assert np.all(np.asarray(result[0]) <= sett.celsius2K)
    assert np.all(np.asarray(result[0]) >= sett.celsius2K + sett.minTIce)
